### PR TITLE
Setup ThreadLocal based CuVSResources usage

### LINKED ISSUE #11: Fix CuVSResources usage
To make changes for implementing the per-thread `CuvsResources` approach using `ThreadLocal`.

### LINKED ISSUE #91: cuvsCagraSearch returned 0[std::bad_alloc: out_of_memory: RMM failure ...
Originates mostly from `TestCuVSRandomizedVectorSearch.testVectorSearch` mainly due to multiple threads trying to use `CuVSResources`. 

This issue occurs since we are using [Lucene test framework's newSearcher(...)](https://github.com/apache/lucene/blob/main/lucene/test-framework/src/java/org/apache/lucene/tests/util/LuceneTestCase.java#L1961-L1964) that randomly uses multiple threads for searching.

```java
[ERROR] com.nvidia.cuvs.lucene.TestCuVSRandomizedVectorSearch.testVectorSearch -- Time elapsed: 0.156 s <<< ERROR!
java.lang.RuntimeException: cuvsCagraSearch returned 0[std::bad_alloc: out_of_memory: RMM failure at:/home/narang/code/cuvs/cpp/build/_deps/rmm-src/cpp/include/rmm/mr/limiting_resource_adaptor.hpp:145: Exceeded memory limit (failed to allocate 4.000000 B)]
	at __randomizedtesting.SeedInfo.seed([DF2F731567F3036C:4B2661F33B2FAEFF]:0)
	at com.nvidia.cuvs.internal.common.Util.checkCuVSError(Util.java:87)
	at com.nvidia.cuvs.internal.CagraIndexImpl.search(CagraIndexImpl.java:309)
	at com.nvidia.cuvs.lucene.CuVS2510GPUVectorsReader.search(CuVS2510GPUVectorsReader.java:455)
	at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsReader.search(PerFieldKnnVectorsFormat.java:311)
.
.
.
```

### PR DESCRIPTION
**Pull request by narangvivek10**
Issue:
Currently, the way the instance of `CuVSResources` was set up as one instance of it at the `CuVS2510GPUVectorsFormat` and `Lucene99AcceleratedHNSWVectorsFormat` level as a class-level member, and its instance was used in a trickle-down fashion in the `CuVS2510GPUVectorsReader`, `CuVS2510GPUVectorsWriter`, and `Lucene99AcceleratedHNSWVectorsWriter` which was causing a rare occurence of failure (Stack trace available in #91).

Fix:
To fix this, I am introducing a ThreadLocal-based mechanism with the new `CuVSResourcesProvider` that gives a better way of providing per-thread copies of `CuVSResources` instances.

Fixes #11 
Fixes #91

### CODE REVIEW

File: src/main/java/com/nvidia/cuvs/lucene/CuVSResourcesProvider.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+
+/**
+ * Provides a mechanism to create ThreadLocal based CuVSResource instances.
+ *
+ * @since 26.02
+ */
+public class CuVSResourcesProvider {
+
+  private static final Logger log = Logger.getLogger(CuVSResourcesProvider.class.getName());
+  private static final ThreadLocal<CuVSResources> cuVSResouces;
```
Comment (mythrocks) [inline src/main/java/com/nvidia/cuvs/lucene/CuVSResourcesProvider.java]:
```suggestion
  private static final ThreadLocal<CuVSResources> cuVSResources;
```

File: src/test/java/com/nvidia/cuvs/lucene/TestCagraToHnswSerializationAndSearch.java [hunk 2]
```diff
@@ -52,7 +53,7 @@ public class TestCagraToHnswSerializationAndSearch extends LuceneTestCase {
 
   @Before
   public void beforeTest() throws Exception {
-    assumeTrue("cuVS not supported", Lucene99AcceleratedHNSWVectorsFormat.supported());
+    assumeTrue("cuVS not supported", isSupported(false));
```
Comment (mythrocks) [inline src/test/java/com/nvidia/cuvs/lucene/TestCagraToHnswSerializationAndSearch.java]: Per prior comment:
```suggestion
    assumeTrue("cuVS not supported", isSupported());
```

**Review by mythrocks — COMMENTED** [review]
Minor nit.  Looks good, otherwise.

File: src/main/java/com/nvidia/cuvs/lucene/CuVS2510GPUVectorsFormat.java [hunk 3]
```diff
@@ -98,19 +96,19 @@ public CuVS2510GPUVectorsFormat(
...
   }
 
   /**
    * Returns a KnnVectorsReader to read the vectors from the index.
    */
   @Override
   public KnnVectorsReader fieldsReader(SegmentReadState state) throws IOException {
-    checkSupported();
-    return new CuVS2510GPUVectorsReader(state, resources, FLAT_VECTORS_FORMAT.fieldsReader(state));
+    isSupported(true);
```
[the remark this answers is not in the document]
Comment (narangvivek10) [reply src/main/java/com/nvidia/cuvs/lucene/CuVS2510GPUVectorsFormat.java]: Done.
